<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PickerContainer" Id="{41f82e27-e9a7-4f3c-81df-9f370712b1f6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PickerContainer EXTENDS ZCore.ObjectContainer
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
  {attribute 'hide'}
  _parent : REFERENCE TO PickerUnit;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{0122d4e3-eab8-4c93-90a8-c11043f50d41}">
      <Declaration><![CDATA[{attribute 'hide' }
METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
  unit : REFERENCE TO PickerUnit;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_parent REF= unit;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>
